CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE ,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT chk_name_length CHECK (LENGTH(name) BETWEEN 2 AND 250),
    CONSTRAINT chk_email_length CHECK (LENGTH(email) BETWEEN 6 AND 254)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE ,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT chk_category_name_length CHECK (LENGTH(name) BETWEEN 1 AND 50)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL,
    confirmed_requests INT,
    created_on TIMESTAMP,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    initiator_id BIGINT NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    published_on TIMESTAMP,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(50) NOT NULL,
    title VARCHAR(120) NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT chk_annotation_length CHECK (LENGTH(annotation) BETWEEN 20 AND 2000),
    CONSTRAINT chk_description_length CHECK (LENGTH(description) BETWEEN 20 AND 7000),
    CONSTRAINT chk_title_length CHECK (LENGTH(title) BETWEEN 3 AND 120),
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_initiator FOREIGN KEY (initiator_id) REFERENCES users(id)
);